routes/web.php
<?php

Route::group([
    'prefix' => 'cms-panel',
    'namespace' => 'CmsPanel',
    'as' => 'cms_panel.',
], function () {
    Route::get('/','DashBoard@index');
    Route::group([
        'prefix' => 'auth',
        'namespace' => 'Auth',
        'as' => 'auth.',
    ], function () {

        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login');
        Route::any('/logout', 'LoginController@logout')->name('logout');

        #Route::any('/password/reset', 'ResetPasswordController@showResetForm')->name('password.reset');

        #Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        #Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        #Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        #Route::post('/password/reset', 'ResetPasswordController@reset');


        #Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
        #Route::post('/register', 'RegisterController@register');


    });
});


Auth::routes();




Route::get('/', function () {
    return view('welcome');
});

app/Models/Permission.php
<?php namespace App\Models;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
}

app/Models/Role.php
<?php
namespace App\Models;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{

    public function roles()
    {
        return $this->belongsToMany('App\Models\Users', 'role_user', 'role_id', 'user_id');
    }

}

app/Models/RoleUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RoleUser extends Model
{
    public $fillable = ['user_id', 'role_id'];

    protected $primaryKey = 'id';
    public function user_id_users()
    {
        return $this->belongsTo('App\Models\Users', 'user_id', 'id');
    }
    public function role_id_roles()
    {
        return $this->belongsTo('App\Models\Role', 'role_id', 'id');
    }

    protected $table = 'role_user';
    public $timestamps = false;

    protected $casts = [
    ];
}

?>

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CmsPanel/DashBoard.php
<?php
namespace App\Http\Controllers\CmsPanel;
class DashBoard extends SetPleaseMainClass
{
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cms_panel/dashboard.blade.php
@extends('layouts.cms_panel.app')

resources/views/layouts/cms_panel/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>

    <link rel="shortcut icon" href="/img/favicon.png">

    <link rel="stylesheet" type="text/css" href="/design/lib/stroke-7/v1.0.1/style.css"/>
    <link rel="stylesheet" type="text/css" href="/design/lib/perfect-scrollbar/v0.6.16/css/perfect-scrollbar.min.css"/>
    <link rel="stylesheet" href="/design/lib/maisonnette/v1.2.1/css/app.min.css" type="text/css"/>
    @yield('head_plus')
</head>
<body>
<nav class="navbar navbar-expand navbar-dark mai-top-header">
    <div class="container"><a href="#" class="navbar-brand"></a>
        <!--Left Menu-->
        <ul class="nav navbar-nav mai-top-nav">
            <li class="nav-item"><a href="/cms-panel" class="nav-link">Home</a></li>

        </ul>
        <!--Icons Menu-->

        <!--User Menu-->
        <ul class="nav navbar-nav float-lg-right mai-user-nav">
            <li class="dropdown nav-item"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle nav-link"> <img src="/design/lib/maisonnette/v1.2.1/img/avatar.jpg"><span class="user-name">Super Admin</span><span class="angle-down s7-angle-down"></span></a>
                <div role="menu" class="dropdown-menu">


                    <a href="{{ route('cms_panel.auth.logout') }}" class="dropdown-item"
                       onclick="event.preventDefault();document.getElementById('logout-form').submit();"> <span class="icon s7-power"> </span> Logout</a>

                    <form id="logout-form" action="{{ route('cms_panel.auth.logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>

                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="mai-wrapper">
    <nav class="navbar navbar-expand-lg mai-sub-header">
        <div class="container">
            <!-- Mega Menu structure-->
            <nav class="navbar navbar-expand-md">
                <button type="button" data-toggle="collapse" data-target="#mai-navbar-collapse" aria-controls="#mai-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler hidden-md-up collapsed">
                    <div class="icon-bar"><span></span><span></span><span></span></div>
                </button>
                <div id="mai-navbar-collapse" class="navbar-collapse collapse mai-nav-tabs">
                    <ul class="nav navbar-nav">
                        <li class="nav-item parent open"><a href="#" role="button" aria-expanded="false" class="nav-link"><span class="icon s7-home"></span><span>Home</span></a>
                            <ul class="mai-nav-tabs-sub mai-sub-nav nav">
                                <li class="nav-item"><a href="/cms-panel" class="nav-link active"><span class="icon s7-monitor"></span><span class="name">Dashboard</span></a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>

        </div>
    </nav>
    <div class="main-content container">

        @yield('content')

    </div>
</div>
<script src="/design/lib/jquery/v3.2.1/jquery.min.js" type="text/javascript"></script>
<script src="/design/lib/perfect-scrollbar/v0.6.16/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="/design/lib/bootstrap/v4.0.0-beta.2/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="/design/lib/maisonnette/v1.2.1/js/app.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function(){
        //initialize the javascript
        App.init();
    });
</script>
</body>
</html>

resources/views/layouts/cms_panel/auth.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('design/lib/stroke-7/v1.0.1/style.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('design/lib/perfect-scrollbar/v0.6.16/css/perfect-scrollbar.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('design/lib/font-awesome/v4.7.0/css/font-awesome.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('design/lib/maisonnette/v1.2.1/css/app.css') }}" type="text/css"/>
</head>
<body class="mai-splash-screen">
@yield('content')
<script src="{{ asset('design/lib/jquery/v3.2.1/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('design/lib/perfect-scrollbar/v0.6.16/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('design/lib/bootstrap/v4.0.0-beta.2/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('design/lib/maisonnette/v1.2.1/js/app.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        //initialize the javascript
        App.init();
    });

</script>
</body>
</html>